import pandas as pd

print("=" * 60)
print("MIMIC-IV-Note — Discharge Summaries")
print("=" * 60)
notes = pd.read_csv("data/mimic/notes/discharge.csv")
print(f"Total discharge notes: {len(notes)}")
print(f"Columns: {list(notes.columns)}")
print(f"\nSample row:")
print(notes.iloc[0])
print(f"\nSample note text (first 500 chars):")
print(notes['text'].iloc[0][:500])

print("\n" + "=" * 60)
print("MIMIC-IV — Diagnosis ICD Codes")
print("=" * 60)
dx = pd.read_csv("data/mimic/structured/diagnoses_icd.csv")
print(f"Total diagnosis rows: {len(dx)}")
print(f"Columns: {list(dx.columns)}")
print(f"\nSample rows:")
print(dx.head(10).to_string(index=False))

print("\n" + "=" * 60)
print("MIMIC-IV — Admissions")
print("=" * 60)
adm = pd.read_csv("data/mimic/structured/admissions.csv")
print(f"Total admissions: {len(adm)}")
print(f"Columns: {list(adm.columns)}")
print(f"\nSample rows:")
print(adm.head(5).to_string(index=False))

print("\n" + "=" * 60)
print("LINKAGE CHECK")
print("=" * 60)
notes_ids = set(notes['hadm_id'].dropna().astype(int))
dx_ids    = set(dx['hadm_id'].dropna().astype(int))
linked    = notes_ids & dx_ids
print(f"Notes with hadm_id:      {len(notes_ids)}")
print(f"Diagnosis rows hadm_id:  {len(dx_ids)}")
print(f"Admissions linkable:     {len(linked)}")
print(f"\nThese {len(linked)} admissions have BOTH a discharge note")
print(f"AND ground truth ICD-10 codes — your benchmark dataset")